version: '3.4'
services:
  api:
    build: ./api
    restart: always
    ports:
     - "5001:5000"
    links:
    - rabbitmq
    - service
    - service_persist
  service:
    build: ./service
    restart: always
    depends_on:
     - rabbitmq
  service_persist:
    build: ./service_persist
    restart: always
    depends_on:
     - rabbitmq
  rabbitmq:
    container_name: nameko.rabbit
    image: rabbitmq:3-management
    restart: always
    ports:
     - "15672:15672"
     - "5671:5672"
